use d-hrsifu-config
# use hrsifu-config

db.task.drop()
db.task.insert({k:NumberInt(1),ct:"Leave Request ##DOCUNUM#: #APPLICANT# applied #NUMDAY# day #LEAVETYPE# from #FDAT# to #TDAT#. What do you think?",bt:"<a href='#APPROVELINK#' class='green'>Approve</a><div class='space-1'></div><a href='#DOCLINK#' class='blue'>Review Request</a>"})
db.task.insert({k:NumberInt(2),ct:"Step 1: Update company profile",bt:"<a href='#SETTINGLINK#' class='green'>Goto Company Profile</a><div class='space-1'></div><a href='#DISMISSLINK#' class='blue'>Dismiss</a>"})
db.task.insert({k:NumberInt(3),ct:"Step 2: Review leave policy",bt:"<a href='#SETTINGLINK#' class='green'>Goto Leave Setting</a><div class='space-1'></div><a href='#DISMISSLINK#' class='blue'>Dismiss</a>"})
db.task.insert({k:NumberInt(4),ct:"Step 3: Update your person information and leave profiles",bt:"<a href='#SETTINGLINK#' class='green'>Update Person Info</a><div class='space-1'></div><a href='#DISMISSLINK#' class='blue'>Dismiss</a>"})
db.task.insert({k:NumberInt(5),ct:"Step 4: Add company holiday",bt:"<a href='#ADDLINK#' class='green'>Add Company Holiday</a><div class='space-1'></div><a href='#SETTINGLINK#' class='green'>Goto Company Calendar</a><div class='space-1'></div><a href='#DISMISSLINK#' class='blue'>Dismiss</a>"})
db.task.insert({k:NumberInt(6),ct:"Step 5: Add company staff",bt:"<a href='#ADDLINK#' class='green'>Add Staff</a><div class='space-1'></div><a href='#SETTINGLINK#' class='green'>Goto Staff Directory</a><div class='space-1'></div><a href='#DISMISSLINK#' class='blue'>Dismiss</a>"})
db.task.insert({k:NumberInt(7),ct:"Leave Request ##DOCUNUM#: #APPLICANT# applied #NUMDAY# day #LEAVETYPE# on #FDAT#. What do you think?",bt:"<a href='#APPROVELINK#' class='green'>Approve</a><div class='space-1'></div><a href='#DOCLINK#' class='blue'>Review Request</a>"})