use d-hrsifu-directory
db.person.update({'wd.wd1':true}, {$set: {'wd.wd1':'Full'}}, { multi: true });
db.person.update({'wd.wd1':false}, {$set: {'wd.wd1':'Off'}}, { multi: true });
db.person.update({'wd.wd2':true}, {$set: {'wd.wd2':'Full'}}, { multi: true });
db.person.update({'wd.wd2':false}, {$set: {'wd.wd2':'Off'}}, { multi: true });
db.person.update({'wd.wd3':true}, {$set: {'wd.wd3':'Full'}}, { multi: true });
db.person.update({'wd.wd3':false}, {$set: {'wd.wd3':'Off'}}, { multi: true });
db.person.update({'wd.wd4':true}, {$set: {'wd.wd4':'Full'}}, { multi: true });
db.person.update({'wd.wd4':false}, {$set: {'wd.wd4':'Off'}}, { multi: true });
db.person.update({'wd.wd5':true}, {$set: {'wd.wd5':'Full'}}, { multi: true });
db.person.update({'wd.wd5':false}, {$set: {'wd.wd5':'Off'}}, { multi: true });
db.person.update({'wd.wd6':true}, {$set: {'wd.wd6':'Full'}}, { multi: true });
db.person.update({'wd.wd6':false}, {$set: {'wd.wd6':'Off'}}, { multi: true });
db.person.update({'wd.wd7':true}, {$set: {'wd.wd7':'Full'}}, { multi: true });
db.person.update({'wd.wd7':false}, {$set: {'wd.wd7':'Off'}}, { multi: true });